# animation
animations=1
animation_type_open=none
animation_type_close=none
animation_fade_in=1
animation_fade_out=1

layer_animations=0
layer_animation_type_open=none
layer_animation_type_close=fade

animation_duration_move=100
animation_duration_open=100
animation_duration_tag=150
animation_duration_close=50
animation_duration_focus=0

animation_curve_open=0.46,1.0,0.29,0.99
animation_curve_move=0.46,1.0,0.29,0.99
animation_curve_tag=0.46,1.0,0.29,0.99
animation_curve_close=0.46,1.0,0.29,0.99
animation_curve_focus=0.46,1.0,0.29,0.99
animation_curve_opafadein=0.46,1.0,0.29,0.99
animation_curve_opafadeout=0.5,0.5,0.5,0.5

tag_animation_direction=1
zoom_initial_ratio=0.4
zoom_end_ratio=0.8
fadein_begin_opacity=0.5
fadeout_begin_opacity=0.8

# blur
blur=1
blur_layer=1
blur_optimized=1
blur_params_radius=5
blur_params_num_passes=2
blur_params_noise=0.02
blur_params_brightness=0.9
blur_params_contrast=0.9
blur_params_saturation=1.2

# shadow
shadows = 0
layer_shadows = 0
shadow_only_floating = 1
shadows_size = 10
shadows_blur = 15
shadows_position_x = 0
shadows_position_y = 0
shadowscolor= 0x000000ff

# border & gaps
borderpx=0
border_radius=0
no_radius_when_single=0
gappih=6
gappiv=6
gappoh=6
gappov=6

scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9

# opacity
focused_opacity=1.0
windowrule=focused_opacity:0.9,appid:code
windowrule=focused_opacity:0.9,appid:foot
windowrule=focused_opacity:0.9,appid:discord
windowrule=focused_opacity:0.9,appid:org.kde.dolphin
windowrule=focused_opacity:0.9,appid:obsidian

unfocused_opacity=1.0
windowrule=unfocused_opacity:0.85,appid:code
windowrule=unfocused_opacity:0.85,appid:foot
windowrule=unfocused_opacity:0.85,appid:discord
windowrule=unfocused_opacity:0.85,appid:org.kde.dolphin
windowrule=unfocused_opacity:0.85,appid:obsidian
