[global]
root_color = 0x{color0.strip}ff
border_color = 0x{background.strip}ff
drop_color = 0x{color11.strip}55
split_color = 0x{color9.strip}FF
focus_color = 0x{foreground.strip}ff
maximized_screen_color = 0x{color10.strip}ff
urgent_color = 0x{color1.strip}ff
scratchpad_color = 0x{color12.strip}ff
global_color = 0x{color13.strip}ff
overlay_color = 0x{color14.strip}ff

# tab bar
tab_bar_decorate_fg_color=0x{foreground.strip}ff
tab_bar_decorate_bg_color=0x{background.strip}ff
tab_bar_decorate_focus_fg_color=0x{color6.strip}ff
tab_bar_decorate_focus_bg_color=0x{color1.strip}ff

