[mgr]
show_hidden = true

[opener]
xournal = [
    { run = "xournalpp %s", orphan = true }
]
sioyek = [
    { run = "sioyek %s", orphan = true }
]

[open]
prepend_rules = [
    { url = "*.xopp", use = "xournal" },
    { url = "*.pdf", use = "sioyek" }
]
