#!/bin/bash

# skhd - rift config

# Change Window Focus
# alt - up                    : rift-cli execute window focus up
# alt - down                  : rift-cli execute window focus down
# alt - left                  : rift-cli execute window focus left
# alt - right                 : rift-cli execute window focus right

# Change Window Focus (VIM-Key)
alt - j                     : rift-cli execute window focus up
alt - k                     : rift-cli execute window focus down
alt - h                     : rift-cli execute window focus left
alt - l                     : rift-cli execute window focus right

# Move Window
# shift + alt - up            : rift-cli execute layout move-node up
# shift + alt - down          : rift-cli execute layout move-node down
# shift + alt - left          : rift-cli execute layout move-node left
# shift + alt - right         : rift-cli execute layout move-node right

# Move Window (VIM-key)
shift + alt - j             : rift-cli execute layout move-node up
shift + alt - k             : rift-cli execute layout move-node down
shift + alt - h             : rift-cli execute layout move-node left
shift + alt - l             : rift-cli execute layout move-node right

# Resize window
shift + alt - 0x1B          : rift-cli execute window resize-shrink
shift + alt - 0x18          : rift-cli execute window resize-grow

# Maximize Window
f11                         : rift-cli execute window toggle-fullscreen
alt - f                     : rift-cli execute window toggle-fullscreen

# Toggle Float
alt - t                     : rift-cli execute window toggle-float

##### SPACE #####
# MOD Window tree
shift + alt - x             : yabai -m space --mirror x-axis
shift + alt - y             : yabai -m space --mirror y-axis
shift + alt - r             : yabai -m space --rotate 90

# CREATE or DESTROY space
shift + alt - c             : yabai -m space --create
shift + alt - 0x33          : yabai -m space --destroy

# BALANCE space
shift + alt - b             : yabai -m space --balance

# SWITCH space LAYOUT
shift + alt - d             : yabai -m space --layout bsp

# Switch to workspaces
alt - 1                     : rift-cli execute workspace switch 1
alt - 2                     : rift-cli execute workspace switch 2
alt - 3                     : rift-cli execute workspace switch 3
alt - 4                     : rift-cli execute workspace switch 4
alt - 5                     : rift-cli execute workspace switch 5
alt - 6                     : rift-cli execute workspace switch 6
alt - 7                     : rift-cli execute workspace switch 7
alt - 8                     : rift-cli execute workspace switch 8
alt - 9                     : rift-cli execute workspace switch 9
alt - 0                     : rift-cli execute workspace switch 0

# Move window to workspace
# need sleep 0.1 otherwise it won't work
shift + alt - 1             : rift-cli execute workspace move-window 1; sleep 0.1; rift-cli execute workspace switch 1
shift + alt - 2             : rift-cli execute workspace move-window 2; sleep 0.1; rift-cli execute workspace switch 2
shift + alt - 3             : rift-cli execute workspace move-window 3; sleep 0.1; rift-cli execute workspace switch 3
shift + alt - 4             : rift-cli execute workspace move-window 4; sleep 0.1; rift-cli execute workspace switch 4
shift + alt - 5             : rift-cli execute workspace move-window 5; sleep 0.1; rift-cli execute workspace switch 5
shift + alt - 6             : rift-cli execute workspace move-window 6; sleep 0.1; rift-cli execute workspace switch 6
shift + alt - 7             : rift-cli execute workspace move-window 7; sleep 0.1; rift-cli execute workspace switch 7
shift + alt - 8             : rift-cli execute workspace move-window 8; sleep 0.1; rift-cli execute workspace switch 8
shift + alt - 9             : rift-cli execute workspace move-window 9; sleep 0.1; rift-cli execute workspace switch 9
shift + alt - 0             : rift-cli execute workspace move-window 0; sleep 0.1; rift-cli execute workspace switch 0

# Move window to workspace (without switch)
ctrl + shift + alt - 1      : rift-cli execute workspace move-window 1
ctrl + shift + alt - 2      : rift-cli execute workspace move-window 2
ctrl + shift + alt - 3      : rift-cli execute workspace move-window 3
ctrl + shift + alt - 4      : rift-cli execute workspace move-window 4
ctrl + shift + alt - 5      : rift-cli execute workspace move-window 5
ctrl + shift + alt - 6      : rift-cli execute workspace move-window 6
ctrl + shift + alt - 7      : rift-cli execute workspace move-window 7
ctrl + shift + alt - 8      : rift-cli execute workspace move-window 8
ctrl + shift + alt - 9      : rift-cli execute workspace move-window 9
ctrl + shift + alt - 0      : rift-cli execute workspace move-window 0

##### Software Shortcut
# Modifier: hyper (caps lock)
hyper - t                   : open -n -b net.kovidgoyal.kitty
hyper - e                   : osascript -e 'tell application "Finder" to make new Finder window' -e 'tell application "Finder" to set target of front window to home'
hyper - f                   : open -b org.mozilla.firefox
hyper - o                   : open -b md.obsidian
hyper - c                   : open -b com.microsoft.VSCode

# Reload skhd
alt - f5                    : skhd --reload; brew services reload sketchybar
alt + shift - f5            : skhd --reload; brew services reload sketchybar; rift service restart