filetype plugin indent on
syntax enable

set number
set relativenumber
set mouse=a

set tabstop=4
set shiftwidth=4
set expandtab
set smartindent

set directory=~/.cache/vim/swap//
set viminfofile=~/.cache/vim/viminfo
