# Overview Setting
hotarea_size=10
enable_hotarea=0
hotarea_disable_on_fullscreen=1
overviewgappi=5
overviewgappo=30
overcircle_center_ratio=0.5

# misc
no_border_when_single=1
axis_bind_apply_timeout=100
focus_on_activate=1
idleinhibit_ignore_visible=0
sloppyfocus=1
warpcursor=1
focus_cross_monitor=0
focusdir_only_zone_overlap=1
focus_cross_tag=0
enable_floating_snap=0
snap_distance=30
drag_tile_to_tile=1
drag_tile_small=1
cursor_theme=GoogleDot-White
cursor_size=24

# keyboard
numlockon=1
xkb_rules_layout=us
xkb_rules_options=caps:escape
repeat_rate=40
repeat_delay=350

# trackpad
disable_trackpad=0
tap_to_click=1
tap_and_drag=1
drag_lock=1
trackpad_natural_scrolling=1
trackpad_disable_while_typing=1
trackpad_left_handed=0
trackpad_middle_button_emulation=0
trackpad_accel_profile=2
trackpad_accel_speed=0.35
swipe_min_threshold=1

# mouse
mouse_natural_scrolling=0

# source
source=~/.cache/wal/colors-mango.conf
source=./init.conf
source=./layouts.conf
source=./binds.conf
source=./effects.conf
source=./monitors.conf
source=./rules.conf
