[global]

# system & hardware
xwayland_persistence = 0
auto_reload_config = 1

# focus & input
focus_on_activate = 1
sloppy_focus = 1
warp_cursor = 1
cursor_hide_timeout = 60

drag_tile_to_tile = 1

axis_bind_apply_timeout = 100
idle_inhibit_ignore_visible = 0
focus_cross_monitor = 0
focus_direction_only_zone_overlap = 1
enable_floating_snap = 0
snap_distance = 30
drag_tile_small = 1

# multi-monitor & tags
focus_cross_monitor = 1
exchange_cross_monitor = 1
focus_cross_tag = 0
view_current_to_back = 0
tag_num = 9
tag_gather = 1

# window behavior
smart_gaps = 0
tag_carousel = 1
