# window
windowrule=focused_opacity:0.9,appid:code
windowrule=focused_opacity:0.9,appid:foot
windowrule=focused_opacity:0.9,appid:discord
windowrule=focused_opacity:0.9,appid:org.kde.dolphin
windowrule=focused_opacity:0.9,appid:obsidian

# layer
layerrule=noblur:1,layer_name:selection
